### ISSUE TITLE
ERROR: Failure: AttributeError (kernelspec)

### ISSUE THREAD

**Issue by gramster** [bollwyvl/nosebook#18]
We have finally upgraded our environment to IPython 3, so I'm trying nosebook again. Now on every notebook I get:

E
======================================================================
ERROR: Failure: AttributeError (kernelspec)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gram/anaconda/lib/python2.7/site-packages/nose/plugins/manager.py", line 154, in generate
    for r in result:
  File "/Users/gram/anaconda/lib/python2.7/site-packages/nosebook.py", line 212, in loadTestsFromFile
    kernel = self.newKernel(nb)
  File "/Users/gram/anaconda/lib/python2.7/site-packages/nosebook.py", line 65, in newKernel
    kernel_name=nb.metadata.kernelspec.name
  File "/Users/gram/anaconda/lib/python2.7/site-packages/IPython/utils/ipstruct.py", line 149, in __getattr__
    raise AttributeError(key)
AttributeError: kernelspec

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)

**Comment by bollwyvl** [comment]
Hm. Now you've gone and confused the matrix, i suppose. I guess it's not
trying to convert anymore, but the notebooks are still in the old format?
